package chap08;

import java.util.Scanner;

// 여러 개의 예외가 발생하는 경우 처리하는 작업
// 사용자가 입력하는 값에 따라 예외가 다르게 발생.
// 1. 사용자가 제대로 값을 입력 : 예외가 발생되지 않으므로 catch블럭 실행되지 않는다.
// 2. 사용자가 나눌 숫자에 0을 입력하면
//			=> ArithmeticException 발생
// 			=> Exception e = new ArithmeticException();
//	   		------------		-----------------------
//             상위타입				하위객체
public class ExceptionTest03 {
	public static void main(String[] args) {
		Scanner key = new Scanner(System.in);
		try {
		System.out.println("start");
		System.out.println("숫자를 입력하세요");
		int num1 = key.nextInt();
		System.out.println("나눌 숫자를 입력하세요");
		int num2 = key.nextInt();
		System.out.println("결과 : "+(num1/num2));
		
		}catch(Exception e) {//모든 예외클래스의 상위클래스
			System.out.println("예외 발생");
			System.out.println("예외메시지:"+e.getMessage());
		}
	}

}
